version: "3"

services:
  message-pusher:
    image: justsong/message-pusher
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro